# Dataset: '`r basename(dataset.dir)`' correlation summary

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
plink.files <- dataset.dir
file_pattern <- func.plink.filename(plink.files)

pheno.desc <- read.phenotype.ordering(plink.files)

plink.data <- read.snps.plink.binary(plink.files, 
                                     file_pattern, 
                                     pheno.desc, 
                                     use.phe = phe.as.fam, 
                                     remove.dups = remove.dups,
                                     maf.threshold = maf.thresh)

X <- plink.data$X
data.m.nona <- plink.data$d
data.p <- plink.data$p
```

## Drugs correlation matrix

```{r results='asis', warning=FALSE, echo=FALSE, message=FALSE, error=FALSE}
idata <- sapply(data.p,as.integer)
idata.cor <- cor(idata, method = "pearson", use = "pairwise.complete.obs")
qplot(x=Var1, y=Var2, data=melt(idata.cor), fill=value, geom="tile")
```

## Genomic regions correlation

```{r results='asis', warning=FALSE, fig.width=15, fig.height=15, echo=FALSE, message=FALSE}
greg.cor <- cor(X, method = "pearson", use = "pairwise.complete.obs")
r <- raster(greg.cor)
plot(r)
```
