```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
medicine <- colnames(tM)[1]

clPheno <- merge(tM, data.m.nona, all = FALSE, by = "row.names")

X <- as.matrix(clPheno[,3:ncol(clPheno)])
y <- clPheno[,2]
y.r <- as.integer(y)
y.r.min <- min(y.r)
y.r.max <- max(y.r)

fit.regularized <- cv.glmnet(X, y, family = "binomial", alpha = 0.7, lambda = seq(1, 0, by = -0.02))
lambda.best <- fit.regularized$lambda.min

last.pos <- as.integer(colnames(X)[ncol(X)])

p <- ifelse(predict(fit.regularized, X, s = lambda.best)[,1] < 0, y.r.min, y.r.max)
summary.t <- update.classification.stats(summary.t, medicine, p, y.r)

model.coef <- coef(fit.regularized, s = lambda.best)
model.coef.nointerc <- model.coef[2:length(model.coef)]
act.idx <- which(abs(model.coef.nointerc) > sign.bound)

act.snps <- as.integer(colnames(X)[act.idx])
act.coef <- model.coef.nointerc[act.idx]
s.f <- data.frame(position = act.idx, bp = act.snps, coeficient = act.coef)

if(length(act.idx) > 0) {
  X.reduced <- X[,act.idx]
  fit.reduced <- cv.glmnet(X.reduced, y, family = "binomial", lambda = seq(1, 0, by = -0.02))
  Y.predicted <- predict(fit.reduced, X.reduced, s = fit.reduced$lambda.min)[,1]
  summary.t.red <- update.classification.stats(summary.t.red, medicine, ifelse(Y.predicted < 0, y.r.min, y.r.max), y.r)
} else {
  # if there're no significant pedictors - always predict 1
  summary.t.red <- update.classification.stats(summary.t.red, medicine, rep(1, length(y.r)), y.r)
}
```

## '`r medicine`' Details

### Elastic Net for Best Lambda

Lambda that minimizes CV error

```{r, warning=FALSE, echo=FALSE}
best.pos <- which(fit.regularized$lambda == lambda.best)
lambda.best
```

Corresponding CV error

```{r, warning=FALSE, echo=FALSE}
fit.regularized$cvm[best.pos]
```

Number of nonzero coefficients (all non-zero)

```{r, warning=FALSE,echo=FALSE}
fit.regularized$nzero[best.pos]
```

Nonzero coefficients*:

```{r, results='asis', warning=FALSE, echo=FALSE}
write.csv(s.f, file = file.path(out.dir, paste0(medicine, ".lm.csv")))
kable(s.f)
```

### Charts

Nonzero coefficients (LASSO):

```{r, warning=FALSE, echo=FALSE}
if(nrow(s.f) > 0) {
  plot(s.f$bp, s.f$coeficient, 
     xlim = c(1, last.pos), xlab = "SNP index", ylab = "coeficient")
} else {
  "Not Available"
}
```

