---
output:
  html_document:
    toc: yes
---
Linear Models
========================================================

```{r setup, echo=FALSE, message=FALSE,warning=FALSE,error=FALSE}
#source("http://bioconductor.org/biocLite.R")
#biocLite(c("snpStats"))

library(ggplot2)
library(reshape2)
library(knitr)
library(glmnet)
library(boot)
library(qqman)
library(raster)

options("scipen" = 100, "digits" = 4)

maf.thresh <- 0.01
sign.bound <- 0.001
emma.sample <- 100
emma.bound <- 0.05

dataset_name <- "dataset_1"
scriptdir <- "D:\\work\\bio\\rlib"
base <- "D:\\work\\bio\\roma_13-march-2015"
plink.files <- file.path(base, dataset_name)
file_pattern <- sub(".bed", "", list.files(plink.files, pattern = "*.bed")[1])

phe.as.fam <- FALSE
remove.dups <- FALSE

out.dir <- file.path(base, "lasso_out", sprintf("%s-%s", dataset_name, file_pattern))
if(!file.exists(out.dir)) dir.create(out.dir, recursive = TRUE)

source(file.path(scriptdir, "readers.R"))

pheno.desc <- read.phenotype.ordering(plink.files)

plink.data <- read.snps.plink.binary(plink.files, 
                                     file_pattern, 
                                     pheno.desc, 
                                     use.phe = phe.as.fam, 
                                     remove.dups = remove.dups,
                                     maf.threshold = maf.thresh)

X <- plink.data$X
data.m.nona <- plink.data$d
data.p <- plink.data$p

summary.table <- NULL
summary.table.red <- NULL
```

# Medicine correlation matrix

```{r, results='asis', warning=FALSE, echo=FALSE}
idata <- sapply(data.p,as.integer)
idata.cor <- cor(idata, method = "pearson", use = "pairwise.complete.obs")
qplot(x=Var1, y=Var2, data=melt(idata.cor), fill=value, geom="tile")
```

# Genomic regions correlation

```{r, results='asis', warning=FALSE, fig.width=15, fig.height=15, echo=FALSE}
greg.cor <- cor(X, method = "pearson", use = "pairwise.complete.obs")
r <- raster(greg.cor)
plot(r)
```

```{r include=FALSE, message=FALSE, warning=FALSE}
out <- NULL
for (i in 1:ncol(data.p)) {
  tM <- data.p[, i, drop = FALSE]
  tM <- tM[!is.na(tM[,1]), 1, drop = F]
  
  # correct available factor values
  tM[,1] <- as.factor(tM[, 1])
  tM.summ <- summary(tM[,1])
  tM.noNA <- length(levels(tM[,1]))
  
  if(all(tM.summ[1:tM.noNA] > 2) && tM.noNA > 1) {
    out <- c(out, knit_child('linear-models-tile.rmd'))
  }
}
```

# Full model prediction accuracy

```{r results='asis', echo=FALSE}
kable(summary.table)
```

# Reduced model prediction accuracy 

```{r results='asis',echo=FALSE}
kable(summary.table.red)
```

`r paste(out, collapse='\n')`