```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
medicine <- colnames(tM)[1]
ignore_cols <- ignore_ds[(ignore_ds$Dataset == dataset_number) & (ignore_ds$Drug == medicine), "Position"]

clPheno <- merge(tM, data.m.nona, all = FALSE, by = "row.names")

X <- as.matrix(clPheno[,3:ncol(clPheno)])

if (length(ignore_cols) > 0) {
  X <- X[,!colnames(X) %in% ignore_cols]
}

y <- clPheno[,2]
y.r <- as.integer(y)
y.r.min <- min(y.r)
y.r.max <- max(y.r)

fit.regularized <- cv.glmnet(X, y, family = "binomial", alpha = 0.7, lambda = seq(1, 0, by = -0.02), nfolds = length(y))
lambda.best <- fit.regularized$lambda.min

last.pos <- as.integer(colnames(X)[ncol(X)])

p.raw <- predict(fit.regularized, X, s = lambda.best)[,1]
p <- ifelse(p.raw < 0, y.r.min, y.r.max)
summary.t <- update.classification.stats(summary.t, medicine, p, y.r)
roc.full <- roc.create.data(y.r, p.raw)

model.coef <- coef(fit.regularized, s = lambda.best)
model.coef.nointerc <- model.coef[2:length(model.coef)]
act.idx <- which(abs(model.coef.nointerc) > sign.bound)

act.snps <- as.integer(colnames(X)[act.idx])
act.coef <- model.coef.nointerc[act.idx]
s.f <- data.frame(position = act.idx, bp = act.snps, coeficient = act.coef)

if (length(act.idx) > 0) {
  X.reduced <- X[,act.idx]
  fit.reduced <- cv.glmnet(X.reduced, y, family = "binomial", lambda = seq(1, 0, by = -0.02), nfolds = length(y))
  Y.predicted <- predict(fit.reduced, X.reduced, s = fit.reduced$lambda.min)[,1]
  summary.t.red <- update.classification.stats(summary.t.red, medicine, ifelse(Y.predicted < 0, y.r.min, y.r.max), y.r)
  roc.reduced <- roc.create.data(y.r, Y.predicted)
  
  coef.reduced <- coef(fit.reduced, s = fit.reduced$lambda.min)
  coef.reduced.nointerc <- coef.reduced[2:length(coef.reduced)]
  act.idx.2 <- which(abs(coef.reduced.nointerc) > sign.bound)
  act.snps.2 <- as.integer(colnames(X.reduced)[act.idx.2])
  act.coef.2 <- coef.reduced.nointerc[act.idx.2]
  s.f.2 <- data.frame(position = act.idx.2, bp = act.snps.2, coeficient = act.coef.2)
} else {
  # if there're no significant pedictors - always predict 1
  Y.predicted <- rep(1, length(y.r))
  summary.t.red <- update.classification.stats(summary.t.red, medicine, Y.predicted, y.r)
  roc.reduced <- roc.create.data(y.r, Y.predicted)
  s.f.2 <- data.frame(position = character(0), bp = character(0), coeficient = character(0))
}

roc.print <- function(roc) {
  ggplot(roc, aes(x = x, y = y)) + xlab("False positives rate") + ylab("True positives rate") +
    geom_line() + geom_point() +
    geom_line(data = data.frame(x = c(0, 1), y = c(0, 1)), aes(x, y, colour = "red")) + theme(legend.position = "none")
}
```

## '`r medicine`' Details

### Elastic Net for Best Lambda

Lambda that minimizes CV error

```{r, warning=FALSE, echo=FALSE}
best.pos <- which(fit.regularized$lambda == lambda.best)
lambda.best
```

Corresponding CV error

```{r, warning=FALSE, echo=FALSE}
fit.regularized$cvm[best.pos]
```

Number of nonzero coefficients (all non-zero)

```{r, warning=FALSE,echo=FALSE}
fit.regularized$nzero[best.pos]
```

Nonzero coefficients*:

```{r, results='asis', warning=FALSE, echo=FALSE}
write.csv(s.f, file = file.path(out.dir, paste0(medicine, ".lm.csv")))
write.csv(s.f.2, file = file.path(out.dir, paste0(medicine, ".lm2.csv")))
kable(s.f)
```

### Charts

Nonzero coefficients (LASSO):

```{r, warning=FALSE, echo=FALSE}
if(nrow(s.f) > 0) {
  ggplot(s.f, aes(x = bp, y = coeficient)) + geom_point() + 
    xlab("SNP index") + ylab("coeficient") +
    geom_line(data = data.frame(x = c(0,last.pos), y = c(0, 0)), aes(x, y, colour = "red")) + theme(legend.position="none")
} else {
  "Not Available"
}
```

ROC curve for full model 

```{r, warning=FALSE, echo=FALSE}
roc.print(roc.full)
```

ROC curve for reduced model 

```{r, warning=FALSE, echo=FALSE}
roc.print(roc.reduced)
```